apiVersion: 1

datasources:
- name: 'Prometheus'
  type: 'prometheus'
  url: 'http://prometheus:9090'
  access: proxy
  isDefault: true
  version: 1
  editable: true
  jsonData:
    timeInterval: '10s'